// Generated by CoffeeScript 1.4.0
var Db, Server, db, dbName, fs, mongo, server,
  _this = this;

fs = require("fs");

dbName = "am-db";

mongo = require('mongodb');

Server = mongo.Server;

Db = mongo.Db;

server = new Server('192.168.4.182', 27017, {
  auto_reconnect: true,
  w: 1
});

db = new Db('test', server);

fs.readFile('./content.txt', "utf-8", function(err, data) {
  return db.open(function(err, db) {
    return db.collection(dbName, function(err, collection) {
      return collection.find({}, {
        "content": 0,
        "_id": 0
      }, {
        limit: 1
      }, function(err, res) {
        return res.toArray(function(err, res) {
          console.log(res);
          return process.exit;
        });
      });
    });
  });
});
