// Generated by CoffeeScript 1.4.0
var f, files, fs, name, path, _i, _len,
  _this = this;

fs = require("fs");

path = require("path");

files = fs.readdirSync("./routes");

for (_i = 0, _len = files.length; _i < _len; _i++) {
  f = files[_i];
  if (path.extname(f) === '.js' && f !== "index.js") {
    name = "./" + f;
    module.exports[path.basename(f, '.js')] = require(name);
  }
}

module.exports.index = function(req, res) {
  return res.render("net", {
    "title": "惯性力场树"
  });
};
