// Generated by CoffeeScript 1.4.0
var Db, db,
  _this = this;

Db = require('../db');

db = Db.db;

module.exports.list = function(req, res) {
  return Db.list("test", function(err, col) {
    return res.send(col);
  });
};

module.exports["new"] = function(req, res) {
  var data;
  data = req.body;
  db = Db.db;
  console.log(data);
  return db.collection('test', function(err, collection) {
    return collection.insert(data, {
      safe: true
    }, function(err, r) {
      if (err) {
        return res.send({
          "result": "error",
          'error_msg': "invalid data"
        });
      } else {
        return res.send({
          "result": "ok"
        });
      }
    });
  });
};

module.exports["delete"] = function(req, res) {
  var data;
  data = req.params;
  console.log(data);
  return db.collection('test', function(err, collection) {
    return collection.remove(function(err, r) {
      if (err) {
        return res.send({
          "result": "error",
          'error_msg': "invalid data"
        });
      } else {
        return res.send({
          "result": "ok"
        });
      }
    });
  });
};

module.exports.put = function(req, res) {
  var data;
  data = req.params;
  console.log(data);
  return res.send("ok");
};

module.exports.get = function(req, res) {
  var data;
  data = req.params.id;
  console.log(data);
  return db.collection('test', function(err, collection) {
    return collection.findOne({
      'User': data
    }, function(err, r) {
      if (err) {
        return res.send({
          "result": "error",
          'error_msg': "invalid data"
        });
      } else {
        console.log(r);
        return res.send({
          "result": "ok",
          'data': r
        });
      }
    });
  });
};
